AnacondaRecipes/snowpark-python-feedstock

recipe/meta.yaml
Changelog: https://github.com/snowflakedb/snowpark-python/blob/v0.7.0/CHANGELOG.md
License: https://github.com/snowflakedb/snowpark-python/blob/v0.7.0/LICENSE.txt
Requirements: https://github.com/snowflakedb/snowpark-python/blob/v0.7.0/setup.py
Actions:
1. Skip py<38 or py>=39 or win32 or s390x
2. Remove noarch: python, and make it arch-specific
3. Add setuptools and wheel in host
4. Add license_family
5. Add dev and doc urls
=> Add snowflake-snowpark-python 0.7.0

recipe/meta.yaml
- Restored snowflake-connector-python>=2.7.4 constraint
- Bumped to version 0.8.0, updated sha256
=> bump to 0.8.0

recipe/meta.yaml
Simple version bump
Bumped snowflake-connector-python dependency to 2.7.11 per
https://github.com/snowflakedb/snowpark-python/blob/main/setup.py#L13
All other dependencies remain identical
=> bump to 0.9.0

recipe/meta.yaml
No changes to dependencies. Still a Python 3.8 build, but there is now flag (off by default) to allow builds for 3.9 and 3.10. These are not going into defaults and will be handled with a separate build.
=> v1.3.0 bump (py38 only)

abs.yaml, recipe/meta.yaml
**Current package info**
| Channel | Downloads | Version | Platforms | License |
| --- | --- | --- | --- | --- |
| main | [![Conda Downloads](https://img.shields.io/conda/dn/main/snowflake-snowpark-python.svg)](https://anaconda.org/main/snowflake-snowpark-python) | [![Conda Version](https://img.shields.io/conda/vn/main/snowflake-snowpark-python.svg)](https://anaconda.org/main/snowflake-snowpark-python) | [![Conda Platforms](https://img.shields.io/conda/pn/main/snowflake-snowpark-python.svg)](https://anaconda.org/main/snowflake-snowpark-python) | ![Conda License](https://img.shields.io/conda/l/main/snowflake-snowpark-python) |
| sfe1ed40 | [![Conda Downloads](https://img.shields.io/conda/dn/sfe1ed40/snowflake-snowpark-python.svg)](https://anaconda.org/sfe1ed40/snowflake-snowpark-python) | …
=> snowflake-snowpark-python 1.8.0 for py311 :snowflake:

recipe/meta.yaml
[Jira Ticket](https://anaconda.atlassian.net/browse/PKG-2876)
[Upstream](https://github.com/snowflakedb/snowpark-python)
[Dependencies ](https://github.com/snowflakedb/snowpark-python/blob/v1.8.0)
- Updated version number and `sha256`
- Updated `host` and `run` sections
=> Snowflake-Snowpark-Python 1.8.0 

recipe/meta.yaml
update to 1.9.0, the lack of py 311 block snowflake-ml-python 1.0.10, goes to default channel
- [upstream](https://github.com/snowflakedb/snowpark-python/tree/v1.9.0)
- [requirements](https://github.com/snowflakedb/snowpark-python/blob/v1.9.0/setup.py)
- enable py 3.11
- add typing extensions
- add cloudpickle for py >= 311
=> update to 1.9.0

recipe/meta.yaml
snowflake-snowpark-python 1.16.0
- [PKG-4768]
- dev_url: https://github.com/snowflakedb/snowpark-python/tree/v1.16.0
- conda-forge: https://github.com/conda-forge/snowflake-snowpark-python-feedstock/blob/main/recipe/meta.yaml
- pypi: https://pypi.org/project/snowflake-snowpark-python/1.16.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-snowpark-python/1.16.0
- upstream diff v1.15.0...v1.16.0: https://github.com/snowflakedb/snowpark-python/compare/v1.15.0...v1.16.0
- bump version, update 1 dep pinning
[PKG-4768]: https://anaconda.atlassian.net/browse/PKG-4768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowflake-snowpark-python 1.16.0

recipe/meta.yaml
snowflake-snowpark-python 1.18.0
- [PKG-4902]
- dev_url (pypi): https://github.com/snowflakedb/snowpark-python/tree/v1.18.0
- diff [v1.17.0...v1.18.0](https://github.com/snowflakedb/snowpark-python/compare/v1.17.0...v1.18.0): https://github.com/snowflakedb/snowpark-python/compare/v1.17.0...v1.18.0
- conda-forge: https://github.com/conda-forge/snowflake-snowpark-python-feedstock/blob/main/recipe/meta.yaml
- pypi: https://pypi.org/project/snowflake-snowpark-python/1.18.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-snowpark-python/1.18.0
- bump version, cleanup `run` from `setuptools` ,`wheels`
[PKG-4902]: https://anaconda.atlassian.net/browse/PKG-4902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> snowflake-snowpark-python 1.18.0

recipe/meta.yaml
snowflake-snowpark-python 1.20.0
- [PKG-5345]
- dev_url (pypi): https://github.com/snowflakedb/snowpark-python/tree/v1.20.0
- [v1.19.0...v1.20.0](https://github.com/snowflakedb/snowpark-python/compare/v1.19.0...v1.20.0) diff: https://github.com/snowflakedb/snowpark-python/compare/v1.19.0...v1.20.0
- pypi: https://pypi.org/project/snowflake-snowpark-python/1.20.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-snowpark-python/1.20.0
- bump version
[PKG-5345]: https://anaconda.atlassian.net/browse/PKG-5345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowflake-snowpark-python 1.20.0

.github/CODEOWNERS, recipe/meta.yaml
snowpark-python 1.21.0
Destination channel: defaults
- [PKG-5546](https://anaconda.atlassian.net/browse/PKG-5546) 
- [Upstream repository](https://github.com/snowflakedb/snowpark-python)
- [Upstream changelog/diff](https://github.com/snowflakedb/snowpark-python/compare/v1.20.0...v1.21.0 )
- version 1.21.0 build
[PKG-5546]: https://anaconda.atlassian.net/browse/PKG-5546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowpark-python 1.21.0

recipe/meta.yaml
snowpark-python 1.21.1
- [PKG-5664](https://anaconda.atlassian.net/browse/PKG-5664) 
- [Upstream repository]( https://github.com/snowflakedb/snowpark-python/tree/v1.21.1)
- [Upstream changelog/diff](https://github.com/snowflakedb/snowpark-python/compare/v1.21.0...v1.21.1)
- 1.21.1 build
[PKG-5664]: https://anaconda.atlassian.net/browse/PKG-5664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowpark-python 1.21.1

recipe/meta.yaml
snowflake-snowpark-python 1.24.0
- [PKG-6028](https://anaconda.atlassian.net/browse/PKG-6028) 
- [Upstream repository](https://github.com/snowflakedb/snowpark-python/tree/v1.24.0)
- [Upstream diff](https://github.com/snowflakedb/snowpark-python/compare/v1.23.0...v1.24.0)
- The only dependency change is for the `modin-development` extra, so nothing is modified in the recipe.
[PKG-6028]: https://anaconda.atlassian.net/browse/PKG-6028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowflake-snowpark-python 1.24.0

recipe/meta.yaml
snowpark-python 1.25.0 
- [PKG-6181]
- dev_url:        https://github.com/snowflakedb/snowpark-python/tree/v1.25.0
- pypi:           https://github.com/snowflakedb/snowpark-python/tree/v1.25.0
- diff: [Comparing v1.24.0...v1.25.0](https://github.com/snowflakedb/snowpark-python/compare/v1.24.0...v1.25.0)
- Upgraded to v1.25.0
[PKG-6181]: https://anaconda.atlassian.net/browse/PKG-6181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowpark-python 1.25.0 

abs.yaml, recipe/meta.yaml
snowflake-snowpark-python 1.25.0
- [PKG-6366]
- [Upstream repository](https://github.com/snowflakedb/snowpark-python/tree/v1.25.0)
- Removed `libprotobuf` from `host`, as it brings in undesirable run exports. Replaced with `protobuf and `mypy-protobuf`.
- Added `abs.yaml` parameters to catch this issue early.
[PKG-6366]: https://anaconda.atlassian.net/browse/PKG-6366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowflake-snowpark-python 1.25.0

recipe/meta.yaml
snowflake-snowpark-python 1.26.0
- [PKG-6475]
- dev_url (pypi): https://github.com/snowflakedb/snowpark-python/tree/v1.26.0
- diff: https://github.com/snowflakedb/snowpark-python/compare/v1.25.0...v1.26.0
- conda-forge: https://github.com/conda-forge/snowflake-snowpark-python-feedstock/blob/main/recipe/meta.yaml
- pypi: https://pypi.org/project/snowflake-snowpark-python/1.26.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-snowpark-python/1.26.0
- bump version
[PKG-6475]: https://anaconda.atlassian.net/browse/PKG-6475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowflake-snowpark-python 1.26.0

recipe/meta.yaml
snowpark-python 1.27.0 
- [PKG-6982]
- dev_url:        https://github.com/snowflakedb/snowpark-python/tree/v1.26.0
- conda_forge:    https://github.com/conda-forge/snowflake-snowpark-python-feedstock/blob/main/recipe/meta.yaml
- pypi:           https://pypi.org/project/snowflake-snowpark-python/1.26.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-snowpark-python/1.26.0
[PKG-6982]: https://anaconda.atlassian.net/browse/PKG-6982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowpark-python 1.27.0 

recipe/meta.yaml
snowpark-python 1.28.0 
- [PKG-7229]
- dev_url:        https://github.com/snowflakedb/snowpark-python/tree/v1.26.0
- conda_forge:    https://github.com/conda-forge/snowflake-snowpark-python-feedstock/blob/main/recipe/meta.yaml
- pypi:           https://pypi.org/project/snowflake-snowpark-python/1.26.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-snowpark-python/1.26.0
[PKG-7229]: https://anaconda.atlassian.net/browse/PKG-7229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowpark-python 1.28.0 

recipe/meta.yaml
snowpark-python 1.29.1 
- [PKG-7391]
- dev_url:        https://github.com/snowflakedb/snowpark-python/tree/v1.29.0
- conda_forge:    https://github.com/conda-forge/snowflake-snowpark-python-feedstock/blob/main/recipe/meta.yaml
- pypi:           https://pypi.org/project/snowflake-snowpark-python/1.29.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-snowpark-python/1.29.0
[PKG-7391]: https://anaconda.atlassian.net/browse/PKG-7391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowpark-python 1.29.1 

recipe/meta.yaml
snowpark-python 1.30.0 
- [PKG-7690]
- dev_url:        https://github.com/snowflakedb/snowpark-python/tree/v1.29.1
- conda_forge:    https://github.com/conda-forge/snowflake-snowpark-python-feedstock/blob/main/recipe/meta.yaml
- pypi:           https://pypi.org/project/snowflake-snowpark-python/1.29.1
- pypi inspector: https://inspector.pypi.io/project/snowflake-snowpark-python/1.29.1
[PKG-7690]: https://anaconda.atlassian.net/browse/PKG-7690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowpark-python 1.30.0 

recipe/meta.yaml
snowpark-python 1.40.0 
- [PKG-10056]
- dev_url:        https://github.com/snowflakedb/snowpark-python/tree/v1.40.0
- conda_forge:    None
- pypi:           https://pypi.org/project/snowpark-python/1.40.0
- pypi inspector: https://inspector.pypi.io/project/snowpark-python/1.40.0
[PKG-10056]: https://anaconda.atlassian.net/browse/PKG-10056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snowpark-python 1.40.0 
